### ISSUE TITLE
Unable to deploy trained model

### ISSUE THREAD

**Issue by shikha1970** [microsoft/Azure-Synapse-Retail-Recommender-Solution-Accelerator#6]
When I run model deployment script, it fails. When I go to environments in AML workspace, I see a custom env by the name myenv. But when I try to build it that fails. Need urgent help.

**Comment by LieBieS** [comment]
Good day, Shikah1970,
Did you find a solution?
You can rename the variable to something else. It appears to be a conflict. I will create a PR to update the issue.

**Comment by Dongbumlee** [comment]
The reason why you've got trouble was curated environment - 'AzureML-PySpark-MmlSpark-0.15' which is not belong to curated environment in AzureML anymore.

So I replaced it with docker container which has been backed by Microsoft in Docker (mcr.microsoft.com/mmlspark/release).
and adding dependencies for score.py into environment.yml file.
